Repository YAPP-Github/Orbit-BE, pull requests merged in 2025-02, with the labels that each got.

#7 [YAF-99] Add PreReservation API with Domain, Persistence, and Tests
  src/main/java/co/yapp/orbit/prereservation/adapter/in/PreReservationController.java
  src/main/java/co/yapp/orbit/prereservation/adapter/in/exception/PreReservationExceptionHandler.java
  src/main/java/co/yapp/orbit/prereservation/adapter/in/request/PreReservationCreateRequest.java
  src/main/java/co/yapp/orbit/prereservation/adapter/out/PreReservationEntity.java
  src/main/java/co/yapp/orbit/prereservation/adapter/out/PreReservationPersistenceAdapter.java
  src/main/java/co/yapp/orbit/prereservation/adapter/out/PreReservationRepository.java
  src/main/java/co/yapp/orbit/prereservation/application/PreReservationService.java
  src/main/java/co/yapp/orbit/prereservation/application/exception/DuplicatePreReservationException.java
  src/main/java/co/yapp/orbit/prereservation/application/exception/InvalidPreReservationCommandException.java
  src/main/java/co/yapp/orbit/prereservation/application/port/in/CreatePreReservationUseCase.java
  src/main/java/co/yapp/orbit/prereservation/application/port/in/PreReservationCommand.java
  src/main/java/co/yapp/orbit/prereservation/application/port/out/SavePreReservationPort.java
  src/main/java/co/yapp/orbit/prereservation/domain/PreReservation.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/co/yapp/orbit/prereservation/adapter/in/PreReservationControllerTest.java
  src/test/java/co/yapp/orbit/prereservation/adapter/out/PreReservationPersistenceAdapterTest.java
  src/test/java/co/yapp/orbit/prereservation/adapter/out/PreReservationRepositoryTest.java
  src/test/java/co/yapp/orbit/prereservation/application/PreReservationServiceTest.java
  src/test/java/co/yapp/orbit/prereservation/domain/PreReservationTest.java
Labels: ✨ feature

#8 [YAF-103] Replace Name with Email in PreReservation API
  src/main/java/co/yapp/orbit/prereservation/adapter/in/PreReservationController.java
  src/main/java/co/yapp/orbit/prereservation/adapter/in/request/PreReservationCreateRequest.java
  src/main/java/co/yapp/orbit/prereservation/adapter/out/PreReservationEntity.java
  src/main/java/co/yapp/orbit/prereservation/adapter/out/PreReservationPersistenceAdapter.java
  src/main/java/co/yapp/orbit/prereservation/adapter/out/PreReservationRepository.java
  src/main/java/co/yapp/orbit/prereservation/application/PreReservationService.java
  src/main/java/co/yapp/orbit/prereservation/application/port/in/PreReservationCommand.java
  src/main/java/co/yapp/orbit/prereservation/application/port/out/SavePreReservationPort.java
  src/main/java/co/yapp/orbit/prereservation/domain/PreReservation.java
  src/test/java/co/yapp/orbit/prereservation/adapter/in/PreReservationControllerTest.java
  src/test/java/co/yapp/orbit/prereservation/adapter/out/PreReservationPersistenceAdapterTest.java
  src/test/java/co/yapp/orbit/prereservation/adapter/out/PreReservationRepositoryTest.java
  src/test/java/co/yapp/orbit/prereservation/application/PreReservationServiceTest.java
  src/test/java/co/yapp/orbit/prereservation/domain/PreReservationTest.java
Labels: 🪛 bug

#6 [YAF-88] Swagger 설정
  .gitignore
  build.gradle
  docker/nginx/Dockerfile-nginx
  docker/nginx/default.conf
  src/main/java/co/yapp/orbit/global/config/SwaggerConfig.java
  src/main/resources/application-local.yml
  src/main/resources/static/swagger-ui/favicon-16x16.png
  src/main/resources/static/swagger-ui/favicon-32x32.png
  src/main/resources/static/swagger-ui/index.css
  src/main/resources/static/swagger-ui/openapi3.json
  src/main/resources/static/swagger-ui/swagger-initializer.js
  src/main/resources/static/swagger-ui/swagger-ui-bundle.js
  src/main/resources/static/swagger-ui/swagger-ui-bundle.js.map
  src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js
  src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js.map
  src/main/resources/static/swagger-ui/swagger-ui.css
  src/main/resources/static/swagger-ui/swagger-ui.css.map
  src/main/resources/static/swagger-ui/swagger-ui.html
Labels: 📋 docs

#9 [YAF-106] Introduce CorsConfig for CORS configuration
  src/main/java/co/yapp/orbit/global/config/CorsConfig.java
Labels: ✨ feature

#11 [YAF-110] Add Discord Webhook Notification for PreReservation Events
  build.gradle
  src/main/java/co/yapp/orbit/prereservation/adapter/out/DiscordWebhookAdapter.java
  src/main/java/co/yapp/orbit/prereservation/application/PreReservationService.java
  src/main/java/co/yapp/orbit/prereservation/application/port/out/NotifyPreReservationPort.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/co/yapp/orbit/prereservation/application/PreReservationServiceTest.java
Labels: ✨ feature

#18 [YAF-108] HTTPS 적용을 위한 Nginx, Certbot 세팅
  .github/workflows/dev-deployment.yml
  docker/docker-compose.yml
  docker/nginx/Dockerfile-nginx
  docker/nginx/conf.d/default.conf
  docker/nginx/default.conf
Labels: ⚙️ chore

#19 [YAF-108] HTTPS 적용 및 Deploy 에러 해결
  .github/workflows/dev-deployment.yml
Labels: ⚙️ chore

#15 [YAF-88] Swagger UI 의존성 추가
  build.gradle
  docker/nginx/Dockerfile-nginx
  src/main/java/co/yapp/orbit/global/config/CorsConfig.java
  src/main/java/co/yapp/orbit/global/config/SwaggerConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/static/docs/openapi3.json
  src/main/resources/static/swagger-ui/favicon-16x16.png
  src/main/resources/static/swagger-ui/favicon-32x32.png
  src/main/resources/static/swagger-ui/index.css
  src/main/resources/static/swagger-ui/swagger-initializer.js
  src/main/resources/static/swagger-ui/swagger-ui-bundle.js
  src/main/resources/static/swagger-ui/swagger-ui-bundle.js.map
  src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js
  src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js.map
  src/main/resources/static/swagger-ui/swagger-ui.css
  src/main/resources/static/swagger-ui/swagger-ui.css.map
  src/main/resources/static/swagger-ui/swagger-ui.html
Labels: 📋 docs

#14 [YAF-102] 운세 생성 API 구현 및 테스트 추가
  .github/workflows/dev-deployment.yml
  .github/workflows/pr-build-test.yml
  build.gradle
  src/main/java/co/yapp/orbit/OrbitApplication.java
  src/main/java/co/yapp/orbit/fortune/adapter/in/FortuneController.java
  src/main/java/co/yapp/orbit/fortune/adapter/in/exception/FortuneExceptionHandler.java
  src/main/java/co/yapp/orbit/fortune/adapter/in/response/LoadFortuneResponse.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortuneAiAdapter.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortuneEntity.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortuneItemEntity.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortunePersistenceAdapter.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/exception/FortuneFetchException.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/request/CreateFortuneRequest.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/request/FortuneAiRequest.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/response/FortuneAiResponse.java
  src/main/java/co/yapp/orbit/fortune/application/CreateFortuneService.java
  src/main/java/co/yapp/orbit/fortune/application/LoadFortuneService.java
  src/main/java/co/yapp/orbit/fortune/application/exception/FortuneParsingException.java
  src/main/java/co/yapp/orbit/fortune/application/exception/InvalidFortuneCommandException.java
  src/main/java/co/yapp/orbit/fortune/application/port/in/CreateFortuneCommand.java
  src/main/java/co/yapp/orbit/fortune/application/port/in/CreateFortuneUseCase.java
  src/main/java/co/yapp/orbit/fortune/application/port/in/LoadFortuneCommand.java
  src/main/java/co/yapp/orbit/fortune/application/port/out/FortuneAiPort.java
  src/main/java/co/yapp/orbit/fortune/application/port/out/SaveFortunePort.java
  src/main/java/co/yapp/orbit/fortune/domain/Fortune.java
  src/main/java/co/yapp/orbit/fortune/domain/FortuneItem.java
  src/main/java/co/yapp/orbit/global/config/JpaAuditingConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/co/yapp/orbit/fortune/adapter/in/FortuneControllerTest.java
  src/test/java/co/yapp/orbit/fortune/adapter/out/FortuneAiAdapterTest.java
  src/test/java/co/yapp/orbit/fortune/application/CreateFortuneServiceTest.java
Labels: ✨ feature

#20 [YAF-102] 환경변수 주입 및 Deploy 오류 해결
  .github/workflows/dev-deployment.yml
  docker/nginx/conf.d/default.conf
  src/main/resources/application.yml
Labels: ⚙️ chore

#21 [YAF-119] 운세 조회 API 추가
  .github/workflows/pr-build-test.yml
  src/main/java/co/yapp/orbit/fortune/adapter/in/FortuneController.java
  src/main/java/co/yapp/orbit/fortune/adapter/in/exception/FortuneExceptionHandler.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortunePersistenceAdapter.java
  src/main/java/co/yapp/orbit/fortune/application/CreateFortuneService.java
  src/main/java/co/yapp/orbit/fortune/application/LoadFortuneService.java
  src/main/java/co/yapp/orbit/fortune/application/exception/FortuneNotFoundException.java
  src/main/java/co/yapp/orbit/fortune/application/port/in/LoadFortuneUseCase.java
  src/main/java/co/yapp/orbit/fortune/application/port/out/LoadFortunePort.java
  src/main/java/co/yapp/orbit/fortune/domain/Fortune.java
  src/test/java/co/yapp/orbit/fortune/adapter/in/FortuneControllerTest.java
  src/test/java/co/yapp/orbit/fortune/adapter/out/FortunePersistenceAdapterTest.java
  src/test/java/co/yapp/orbit/fortune/application/LoadFortuneServiceTest.java
Labels: ✨ feature

#22 [YAF-120] Fortune 도메인 변경 및 프롬프트 수정
  .gitignore
  build.gradle
  src/main/java/co/yapp/orbit/fortune/adapter/in/FortuneController.java
  src/main/java/co/yapp/orbit/fortune/adapter/in/exception/FortuneExceptionHandler.java
  src/main/java/co/yapp/orbit/fortune/adapter/in/response/FortuneResponse.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortuneAiAdapter.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortuneEntity.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortuneGenerationAdapter.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortuneItemEntity.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortunePersistenceAdapter.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/exception/FortuneFetchException.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/exception/FortuneParsingException.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/exception/FortunePromptLoadException.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/exception/WebClientFetchException.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/request/CreateFortuneRequest.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/request/FortuneGenerationRequest.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/response/CreateFortuneResponse.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/response/FortuneGenerationResponse.java
  src/main/java/co/yapp/orbit/fortune/application/CreateFortuneService.java
  src/main/java/co/yapp/orbit/fortune/application/exception/FortuneCreateInvalidUserException.java
  src/main/java/co/yapp/orbit/fortune/application/port/out/FortuneAiPort.java
  src/main/java/co/yapp/orbit/fortune/application/port/out/FortuneGenerationPort.java
  src/main/java/co/yapp/orbit/fortune/domain/FortuneItem.java
  src/main/java/co/yapp/orbit/global/config/JsonConfig.java
  src/main/java/co/yapp/orbit/user/adapter/out/UserIntegrationAdapter.java
  src/main/java/co/yapp/orbit/user/adapter/out/response/UserInfoResponse.java
  src/main/java/co/yapp/orbit/user/application/port/out/UserApiPort.java
  src/main/resources/static/docs/openapi3.json
  src/main/resources/templates/prompts/fortune_prompt_v1.json
  src/test/java/co/yapp/orbit/fortune/adapter/in/FortuneControllerTest.java
  src/test/java/co/yapp/orbit/fortune/adapter/out/FortuneAiAdapterTest.java
  src/test/java/co/yapp/orbit/fortune/adapter/out/FortuneGenerationAdapterTest.java
  src/test/java/co/yapp/orbit/fortune/adapter/out/FortunePersistenceAdapterTest.java
  src/test/java/co/yapp/orbit/fortune/application/CreateFortuneServiceTest.java
  src/test/java/co/yapp/orbit/fortune/application/LoadFortuneServiceTest.java
Labels: 🔥 hotfix

#23 [YAF-127] Add OpenAPI 3 spec generation and API documentation tests
  src/main/resources/static/docs/openapi3.json
  src/test/java/co/yapp/orbit/prereservation/adapter/in/PreReservationControllerDocumentTest.java
  src/test/java/co/yapp/orbit/user/adapter/in/UserControllerDocumentTest.java
Labels: 📋 docs, ⚙️ chore

#25 [YAF-129] 운세 도메인 변경 및 프롬프트 수정
  src/main/java/co/yapp/orbit/fortune/adapter/in/response/FortuneResponse.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortuneEntity.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortuneGenerationAdapter.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortunePersistenceAdapter.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/response/CreateFortuneResponse.java
  src/main/java/co/yapp/orbit/fortune/application/CreateFortuneService.java
  src/main/java/co/yapp/orbit/fortune/domain/Fortune.java
  src/main/java/co/yapp/orbit/user/adapter/out/UserIntegrationAdapter.java
  src/main/resources/static/docs/openapi3.json
  src/main/resources/templates/prompts/fortune_prompt_v1.json
  src/main/resources/templates/prompts/fortune_prompt_v2.json
  src/test/java/co/yapp/orbit/fortune/adapter/in/FortuneControllerTest.java
  src/test/java/co/yapp/orbit/fortune/adapter/out/FortunePersistenceAdapterTest.java
  src/test/java/co/yapp/orbit/fortune/application/CreateFortuneServiceTest.java
  src/test/java/co/yapp/orbit/fortune/application/LoadFortuneServiceTest.java
Labels: 🔥 hotfix

#26 [YAF-130] 프롬프트 최적화 및 Gemini API 파라미터 추가
  src/main/java/co/yapp/orbit/fortune/adapter/out/FortuneGenerationAdapter.java
  src/main/java/co/yapp/orbit/fortune/adapter/out/request/FortuneGenerationRequest.java
  src/main/resources/templates/prompts/fortune_prompt_v2.json
Labels: 🔥 hotfix

#27 [YAF-130] 프롬프트 출력 조건 개선
  src/main/resources/templates/prompts/fortune_prompt_v2.json
Labels: 🔥 hotfix
